---
# Install a few selected packages that we need on every machine
- name: Install basic packages
  apt:
    state: latest
    name: "{{ item }}"
    force_apt_get: yes
    install_recommends: no
    update_cache: yes
  loop:
    - docker.io
    - python3
    - python3-pip
- name: Make sure that setuptools and wheel are up to date
  command: python3 -m pip install --upgrade pip setuptools wheel
- name: Install Ansible
  command: pip3 install ansible
