---
# Run Terraform, collect output and build inventory
- name: Run Terraform and build inventory
  hosts: localhost
  roles:
  - terraform

# Now wait until all machines are readable 
- name: Wait for all machines to become ready
  hosts: all
  gather_facts: no
  tasks:
  - name: Wait for machine to become reachable
    wait_for_connection:
      delay: 30
      sleep: 10
